version: '3.8'

services:
  db:
    # Usamos uma imagem oficial do pgvector baseada no PostgreSQL 16
    image: pgvector/pgvector:pg16
    container_name: rag_postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: