// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using New.AI.Chat.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace New.AI.Chat.Migrations
{
    [DbContext(typeof(AIDbContext))]
    [Migration("20260312154852_CRIAR_ESTRUTURA_TABELAS_HIERARQUICAS")]
    partial class CRIAR_ESTRUTURA_TABELAS_HIERARQUICAS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("New.AI.Chat.Models.KnowledgeDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)");

                    b.Property<string>("Font")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("KnowledgeDocument", (string)null);
                });

            modelBuilder.Entity("New.AI.Chat.Models.KnowledgeDocumentHighGranularity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("KDHG_ID");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("KDHG_ContentText");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)")
                        .HasColumnName("KDHG_Embedding");

                    b.Property<Guid>("LowGranularityId")
                        .HasColumnType("uuid")
                        .HasColumnName("KDHG_LowGranularityId");

                    b.HasKey("Id");

                    b.HasIndex("ContentText");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ContentText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("ContentText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_l2_ops" });

                    b.HasIndex("LowGranularityId");

                    b.ToTable("KDHighGranularity_KDHG", (string)null);
                });

            modelBuilder.Entity("New.AI.Chat.Models.KnowledgeDocumentInformation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("KDI_ID");

                    b.Property<string>("ContextText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("KDI_ContextText");

                    b.Property<DateTime>("DateFirstInsertion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("KDI_DateFirstInsertion");

                    b.Property<DateTime>("DateLastInsertion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("KDI_DateLastInsertion");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("KDI_FileName");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("KDI_Format");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("KDI_Size");

                    b.HasKey("Id");

                    b.ToTable("KDInformation_KDI", (string)null);
                });

            modelBuilder.Entity("New.AI.Chat.Models.KnowledgeDocumentLowGranularity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("KDLG_ID");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("KDLG_ContextText");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)")
                        .HasColumnName("KDLG_Embedding");

                    b.Property<Guid>("InformationId")
                        .HasColumnType("uuid")
                        .HasColumnName("KDLG_InformationId");

                    b.HasKey("Id");

                    b.HasIndex("ContentText");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ContentText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("ContentText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_l2_ops" });

                    b.HasIndex("InformationId");

                    b.ToTable("KDLowGranularity_KDLG", (string)null);
                });

            modelBuilder.Entity("New.AI.Chat.Models.KnowledgeDocumentHighGranularity", b =>
                {
                    b.HasOne("New.AI.Chat.Models.KnowledgeDocumentLowGranularity", "KnowledgeDocumentLowGranularity")
                        .WithMany("HighGranularityList")
                        .HasForeignKey("LowGranularityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgeDocumentLowGranularity");
                });

            modelBuilder.Entity("New.AI.Chat.Models.KnowledgeDocumentLowGranularity", b =>
                {
                    b.HasOne("New.AI.Chat.Models.KnowledgeDocumentInformation", "KnowledgeDocumentInformation")
                        .WithMany("LowGranularityList")
                        .HasForeignKey("InformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnowledgeDocumentInformation");
                });

            modelBuilder.Entity("New.AI.Chat.Models.KnowledgeDocumentInformation", b =>
                {
                    b.Navigation("LowGranularityList");
                });

            modelBuilder.Entity("New.AI.Chat.Models.KnowledgeDocumentLowGranularity", b =>
                {
                    b.Navigation("HighGranularityList");
                });
#pragma warning restore 612, 618
        }
    }
}
